// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/audit.proto

/*
Package audit is a generated protocol buffer package.

It is generated from these files:
	api/audit.proto

It has these top-level messages:
	AuditRecord
	AuditRecords
	Authentication
	Response
	Billing
	RetireQuery
	IDQuery
	ListQuery
*/
package audit

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import entity "github.com/kubecorp/coral/sdk/go/entity"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuditRecord struct {
	Id             string          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CreatedTime    int64           `protobuf:"varint,2,opt,name=createdTime" json:"createdTime,omitempty"`
	UpdateTime     int64           `protobuf:"varint,3,opt,name=updateTime" json:"updateTime,omitempty"`
	RequestID      string          `protobuf:"bytes,4,opt,name=requestID" json:"requestID,omitempty"`
	Entity         *entity.Entity  `protobuf:"bytes,5,opt,name=entity" json:"entity,omitempty"`
	Authentication *Authentication `protobuf:"bytes,6,opt,name=authentication" json:"authentication,omitempty"`
	Response       *Response       `protobuf:"bytes,7,opt,name=response" json:"response,omitempty"`
	Billing        *Billing        `protobuf:"bytes,8,opt,name=billing" json:"billing,omitempty"`
}

func (m *AuditRecord) Reset()                    { *m = AuditRecord{} }
func (m *AuditRecord) String() string            { return proto.CompactTextString(m) }
func (*AuditRecord) ProtoMessage()               {}
func (*AuditRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuditRecord) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuditRecord) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *AuditRecord) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *AuditRecord) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func (m *AuditRecord) GetEntity() *entity.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *AuditRecord) GetAuthentication() *Authentication {
	if m != nil {
		return m.Authentication
	}
	return nil
}

func (m *AuditRecord) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *AuditRecord) GetBilling() *Billing {
	if m != nil {
		return m.Billing
	}
	return nil
}

type AuditRecords struct {
	AuditRecords []*AuditRecord `protobuf:"bytes,1,rep,name=auditRecords" json:"auditRecords,omitempty"`
}

func (m *AuditRecords) Reset()                    { *m = AuditRecords{} }
func (m *AuditRecords) String() string            { return proto.CompactTextString(m) }
func (*AuditRecords) ProtoMessage()               {}
func (*AuditRecords) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuditRecords) GetAuditRecords() []*AuditRecord {
	if m != nil {
		return m.AuditRecords
	}
	return nil
}

type Authentication struct {
	Type   string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Issuer string `protobuf:"bytes,3,opt,name=issuer" json:"issuer,omitempty"`
}

func (m *Authentication) Reset()                    { *m = Authentication{} }
func (m *Authentication) String() string            { return proto.CompactTextString(m) }
func (*Authentication) ProtoMessage()               {}
func (*Authentication) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Authentication) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Authentication) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Authentication) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

type Response struct {
	Code int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Body string `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Billing struct {
	Billed  bool   `protobuf:"varint,1,opt,name=billed" json:"billed,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Ammount string `protobuf:"bytes,3,opt,name=ammount" json:"ammount,omitempty"`
}

func (m *Billing) Reset()                    { *m = Billing{} }
func (m *Billing) String() string            { return proto.CompactTextString(m) }
func (*Billing) ProtoMessage()               {}
func (*Billing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Billing) GetBilled() bool {
	if m != nil {
		return m.Billed
	}
	return false
}

func (m *Billing) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Billing) GetAmmount() string {
	if m != nil {
		return m.Ammount
	}
	return ""
}

type RetireQuery struct {
	DaysBack int32 `protobuf:"varint,1,opt,name=daysBack" json:"daysBack,omitempty"`
}

func (m *RetireQuery) Reset()                    { *m = RetireQuery{} }
func (m *RetireQuery) String() string            { return proto.CompactTextString(m) }
func (*RetireQuery) ProtoMessage()               {}
func (*RetireQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RetireQuery) GetDaysBack() int32 {
	if m != nil {
		return m.DaysBack
	}
	return 0
}

type IDQuery struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *IDQuery) Reset()                    { *m = IDQuery{} }
func (m *IDQuery) String() string            { return proto.CompactTextString(m) }
func (*IDQuery) ProtoMessage()               {}
func (*IDQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *IDQuery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IDQuery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListQuery struct {
	EntityAttributes map[string]string `protobuf:"bytes,1,rep,name=entityAttributes" json:"entityAttributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ListQuery) Reset()                    { *m = ListQuery{} }
func (m *ListQuery) String() string            { return proto.CompactTextString(m) }
func (*ListQuery) ProtoMessage()               {}
func (*ListQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ListQuery) GetEntityAttributes() map[string]string {
	if m != nil {
		return m.EntityAttributes
	}
	return nil
}

func init() {
	proto.RegisterType((*AuditRecord)(nil), "audit.AuditRecord")
	proto.RegisterType((*AuditRecords)(nil), "audit.AuditRecords")
	proto.RegisterType((*Authentication)(nil), "audit.Authentication")
	proto.RegisterType((*Response)(nil), "audit.Response")
	proto.RegisterType((*Billing)(nil), "audit.Billing")
	proto.RegisterType((*RetireQuery)(nil), "audit.RetireQuery")
	proto.RegisterType((*IDQuery)(nil), "audit.IDQuery")
	proto.RegisterType((*ListQuery)(nil), "audit.ListQuery")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuditService service

type AuditServiceClient interface {
	GetRecord(ctx context.Context, in *IDQuery, opts ...grpc.CallOption) (*AuditRecord, error)
	ListRecords(ctx context.Context, in *ListQuery, opts ...grpc.CallOption) (*AuditRecords, error)
	CreateRecord(ctx context.Context, in *AuditRecord, opts ...grpc.CallOption) (*entity.Empty, error)
	RetireRecords(ctx context.Context, in *RetireQuery, opts ...grpc.CallOption) (*entity.Empty, error)
}

type auditServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuditServiceClient(cc *grpc.ClientConn) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) GetRecord(ctx context.Context, in *IDQuery, opts ...grpc.CallOption) (*AuditRecord, error) {
	out := new(AuditRecord)
	err := grpc.Invoke(ctx, "/audit.AuditService/GetRecord", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) ListRecords(ctx context.Context, in *ListQuery, opts ...grpc.CallOption) (*AuditRecords, error) {
	out := new(AuditRecords)
	err := grpc.Invoke(ctx, "/audit.AuditService/ListRecords", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) CreateRecord(ctx context.Context, in *AuditRecord, opts ...grpc.CallOption) (*entity.Empty, error) {
	out := new(entity.Empty)
	err := grpc.Invoke(ctx, "/audit.AuditService/CreateRecord", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) RetireRecords(ctx context.Context, in *RetireQuery, opts ...grpc.CallOption) (*entity.Empty, error) {
	out := new(entity.Empty)
	err := grpc.Invoke(ctx, "/audit.AuditService/RetireRecords", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuditService service

type AuditServiceServer interface {
	GetRecord(context.Context, *IDQuery) (*AuditRecord, error)
	ListRecords(context.Context, *ListQuery) (*AuditRecords, error)
	CreateRecord(context.Context, *AuditRecord) (*entity.Empty, error)
	RetireRecords(context.Context, *RetireQuery) (*entity.Empty, error)
}

func RegisterAuditServiceServer(s *grpc.Server, srv AuditServiceServer) {
	s.RegisterService(&_AuditService_serviceDesc, srv)
}

func _AuditService_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/audit.AuditService/GetRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetRecord(ctx, req.(*IDQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_ListRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ListRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/audit.AuditService/ListRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ListRecords(ctx, req.(*ListQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_CreateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).CreateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/audit.AuditService/CreateRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).CreateRecord(ctx, req.(*AuditRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_RetireRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetireQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).RetireRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/audit.AuditService/RetireRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).RetireRecords(ctx, req.(*RetireQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuditService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "audit.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecord",
			Handler:    _AuditService_GetRecord_Handler,
		},
		{
			MethodName: "ListRecords",
			Handler:    _AuditService_ListRecords_Handler,
		},
		{
			MethodName: "CreateRecord",
			Handler:    _AuditService_CreateRecord_Handler,
		},
		{
			MethodName: "RetireRecords",
			Handler:    _AuditService_RetireRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/audit.proto",
}

func init() { proto.RegisterFile("api/audit.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 659 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xcf, 0x6a, 0xdb, 0x4e,
	0x10, 0x46, 0x76, 0xfc, 0x47, 0x63, 0xc7, 0x31, 0x93, 0xe4, 0x87, 0x7e, 0x22, 0x14, 0xa3, 0x43,
	0x70, 0x53, 0x6a, 0x81, 0x0b, 0xa5, 0x04, 0x7a, 0xc8, 0x1f, 0xa7, 0x04, 0xda, 0x43, 0xb7, 0xed,
	0xa5, 0xb7, 0xb5, 0xb4, 0x38, 0x8b, 0x6d, 0xad, 0xba, 0x5a, 0x05, 0x44, 0xe9, 0xa5, 0xaf, 0xd0,
	0x57, 0xe8, 0x1b, 0xf4, 0xd8, 0xc7, 0xe8, 0x2b, 0xf4, 0x41, 0x8a, 0x76, 0x57, 0x8a, 0xe3, 0xe4,
	0xa4, 0xfd, 0x66, 0xbe, 0xf9, 0xf8, 0x66, 0x67, 0x56, 0xb0, 0x47, 0x53, 0x1e, 0xd2, 0x3c, 0xe6,
	0x6a, 0x92, 0x4a, 0xa1, 0x04, 0xb6, 0x34, 0xf0, 0x8f, 0x16, 0x42, 0x2c, 0x56, 0x2c, 0xd4, 0xe9,
	0x24, 0x11, 0x8a, 0x2a, 0x2e, 0x92, 0xcc, 0x90, 0xfc, 0x61, 0x19, 0x66, 0x89, 0xe2, 0xaa, 0x30,
	0x91, 0xe0, 0x77, 0x03, 0x7a, 0x67, 0x65, 0x25, 0x61, 0x91, 0x90, 0x31, 0x0e, 0xa0, 0xc1, 0x63,
	0xcf, 0x19, 0x39, 0x63, 0x97, 0x34, 0x78, 0x8c, 0x23, 0xe8, 0x45, 0x92, 0x51, 0xc5, 0xe2, 0x8f,
	0x7c, 0xcd, 0xbc, 0xc6, 0xc8, 0x19, 0x37, 0xc9, 0x66, 0x08, 0x9f, 0x00, 0xe4, 0x69, 0x4c, 0x15,
	0xd3, 0x84, 0xa6, 0x26, 0x6c, 0x44, 0xf0, 0x08, 0x5c, 0xc9, 0xbe, 0xe4, 0x2c, 0x53, 0xd7, 0x97,
	0xde, 0x8e, 0x16, 0xbe, 0x0b, 0xe0, 0x31, 0xb4, 0x8d, 0x1f, 0xaf, 0x35, 0x72, 0xc6, 0xbd, 0xe9,
	0x60, 0x62, 0xed, 0xcd, 0xf4, 0x87, 0xd8, 0x2c, 0xbe, 0x86, 0x01, 0xcd, 0xd5, 0x4d, 0x89, 0x22,
	0xdd, 0x92, 0xd7, 0xd6, 0xfc, 0xc3, 0x89, 0xb9, 0x84, 0xb3, 0x7b, 0x49, 0xb2, 0x45, 0xc6, 0x67,
	0xd0, 0x95, 0x2c, 0x4b, 0x45, 0x92, 0x31, 0xaf, 0xa3, 0x0b, 0xf7, 0x6c, 0x21, 0xb1, 0x61, 0x52,
	0x13, 0x70, 0x0c, 0x9d, 0x39, 0x5f, 0xad, 0x78, 0xb2, 0xf0, 0xba, 0xd6, 0x94, 0xe1, 0x9e, 0x9b,
	0x28, 0xa9, 0xd2, 0xc1, 0x15, 0xf4, 0x37, 0x2e, 0x2f, 0xc3, 0x97, 0xd0, 0xa7, 0x1b, 0xd8, 0x73,
	0x46, 0xcd, 0x71, 0x6f, 0x8a, 0xb5, 0xc7, 0x3a, 0x45, 0xee, 0xf1, 0x02, 0x02, 0x83, 0xfb, 0x0d,
	0x20, 0xc2, 0x8e, 0x2a, 0x52, 0x66, 0x27, 0xa1, 0xcf, 0x78, 0x00, 0x2d, 0x25, 0x96, 0x2c, 0xd1,
	0x53, 0x70, 0x89, 0x01, 0xf8, 0x1f, 0xb4, 0x79, 0x96, 0xe5, 0x4c, 0xea, 0xbb, 0x77, 0x89, 0x45,
	0xc1, 0x14, 0xba, 0x55, 0x6f, 0xa5, 0x5a, 0x24, 0x62, 0xa3, 0xd6, 0x22, 0xfa, 0x5c, 0xc6, 0xe6,
	0x22, 0x2e, 0xac, 0x98, 0x3e, 0x07, 0x9f, 0xa0, 0x63, 0x7b, 0x2c, 0x65, 0xcb, 0x2e, 0x99, 0x59,
	0x86, 0x2e, 0xb1, 0x08, 0x3d, 0xe8, 0xd0, 0x28, 0x12, 0x79, 0xa2, 0x6c, 0x65, 0x05, 0x75, 0x66,
	0xbd, 0xd6, 0x99, 0xa6, 0xcd, 0x18, 0x18, 0x3c, 0x85, 0x1e, 0x61, 0x8a, 0x4b, 0xf6, 0x3e, 0x67,
	0xb2, 0x40, 0x1f, 0xba, 0x31, 0x2d, 0xb2, 0x73, 0x1a, 0x2d, 0xad, 0xa3, 0x1a, 0x07, 0xcf, 0xa1,
	0x73, 0x7d, 0x69, 0x68, 0xdb, 0xab, 0x88, 0xb0, 0x93, 0x50, 0xbb, 0x83, 0x2e, 0xd1, 0xe7, 0xe0,
	0xa7, 0x03, 0xee, 0x5b, 0x9e, 0x29, 0x53, 0x41, 0x60, 0x68, 0xd6, 0xe5, 0x4c, 0x29, 0xc9, 0xe7,
	0xb9, 0x62, 0xd5, 0x08, 0x8e, 0xed, 0x08, 0x6a, 0xae, 0xdd, 0xaf, 0x3b, 0xe2, 0x2c, 0x51, 0xb2,
	0x20, 0x0f, 0xea, 0xfd, 0x0b, 0x38, 0x7c, 0x94, 0x8a, 0x43, 0x68, 0x2e, 0x59, 0x61, 0xfd, 0x95,
	0xc7, 0x72, 0x3e, 0xb7, 0x74, 0x95, 0x57, 0x0e, 0x0d, 0x38, 0x6d, 0xbc, 0x72, 0xa6, 0xbf, 0x1a,
	0x76, 0x51, 0x3e, 0x30, 0x79, 0xcb, 0x23, 0x86, 0x33, 0x70, 0xdf, 0xb0, 0xfa, 0xcd, 0x59, 0x73,
	0xb6, 0x71, 0xff, 0x91, 0x7d, 0x09, 0x0e, 0xbe, 0xff, 0xf9, 0xfb, 0xa3, 0x31, 0xc0, 0x7e, 0x28,
	0x75, 0x20, 0xfc, 0xca, 0xe3, 0x6f, 0x78, 0x05, 0xbd, 0xb2, 0xa3, 0x6a, 0xfd, 0x86, 0xdb, 0x5d,
	0xfa, 0xfb, 0x0f, 0xa5, 0xb2, 0x60, 0xa8, 0xb5, 0x00, 0xbb, 0x56, 0x2b, 0xc3, 0x19, 0xf4, 0x2f,
	0xf4, 0x93, 0xb6, 0x8e, 0x1e, 0x71, 0xe0, 0xef, 0xd6, 0x2f, 0x73, 0x9d, 0xaa, 0x22, 0x40, 0x2d,
	0xd2, 0x0f, 0x3a, 0x56, 0xe4, 0xd4, 0x39, 0xc1, 0x77, 0xb0, 0x6b, 0xe6, 0x5c, 0x19, 0xc2, 0xfa,
	0x91, 0xd5, 0xd3, 0xdf, 0xd6, 0xf9, 0x5f, 0xeb, 0xec, 0x07, 0x83, 0xaa, 0x31, 0xa9, 0xb9, 0xa7,
	0xce, 0xc9, 0xf9, 0xf8, 0xf3, 0xf1, 0x82, 0xab, 0x9b, 0x7c, 0x3e, 0x89, 0xc4, 0x3a, 0x5c, 0xe6,
	0xf3, 0x92, 0x90, 0x86, 0x91, 0x90, 0x74, 0x15, 0x66, 0xf1, 0x32, 0x5c, 0x08, 0xf3, 0x0b, 0x9c,
	0xb7, 0xf5, 0xcf, 0xec, 0xc5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0x40, 0x12, 0xa7, 0x16,
	0x05, 0x00, 0x00,
}
