workspace:
  base: /go
  path: src/github.com/kubecorp/coral
pipeline:
  deps:
    image: golang:1.9
    commands:
      - go get github.com/Masterminds/glide && glide up
  build:
    image: golang:1.9
    commands:
      - go build
  test:
    image: golang:1.9
    commands:
      - go test ./...
