version: "3"
services:
  build:
    image: golang:1.9
    container_name: build
    volumes:
      - "./:/go/src/github.com/aunem/coral"
    working_dir: /go/src/github.com/aunem/coral
    command: make build
  deps:
    image: golang:1.9
    container_name: build
    volumes:
      - "./:/go/src/github.com/aunem/coral"
    working_dir: /go/src/github.com/aunem/coral
    command: make deps
    