// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/house.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	api/house.proto

It has these top-level messages:
	InputRequest
	OutputResponse
	Err
	Empty
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InputRequest struct {
	Id           string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Zipcode      string `protobuf:"bytes,2,opt,name=zipcode" json:"zipcode,omitempty"`
	Bedrooms     string `protobuf:"bytes,3,opt,name=bedrooms" json:"bedrooms,omitempty"`
	Baths        string `protobuf:"bytes,4,opt,name=baths" json:"baths,omitempty"`
	Neighborhood string `protobuf:"bytes,5,opt,name=neighborhood" json:"neighborhood,omitempty"`
}

func (m *InputRequest) Reset()                    { *m = InputRequest{} }
func (m *InputRequest) String() string            { return proto.CompactTextString(m) }
func (*InputRequest) ProtoMessage()               {}
func (*InputRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InputRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InputRequest) GetZipcode() string {
	if m != nil {
		return m.Zipcode
	}
	return ""
}

func (m *InputRequest) GetBedrooms() string {
	if m != nil {
		return m.Bedrooms
	}
	return ""
}

func (m *InputRequest) GetBaths() string {
	if m != nil {
		return m.Baths
	}
	return ""
}

func (m *InputRequest) GetNeighborhood() string {
	if m != nil {
		return m.Neighborhood
	}
	return ""
}

type OutputResponse struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Price int64  `protobuf:"varint,2,opt,name=price" json:"price,omitempty"`
}

func (m *OutputResponse) Reset()                    { *m = OutputResponse{} }
func (m *OutputResponse) String() string            { return proto.CompactTextString(m) }
func (*OutputResponse) ProtoMessage()               {}
func (*OutputResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OutputResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OutputResponse) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type Err struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Loss int64  `protobuf:"varint,2,opt,name=loss" json:"loss,omitempty"`
}

func (m *Err) Reset()                    { *m = Err{} }
func (m *Err) String() string            { return proto.CompactTextString(m) }
func (*Err) ProtoMessage()               {}
func (*Err) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Err) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Err) GetLoss() int64 {
	if m != nil {
		return m.Loss
	}
	return 0
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*InputRequest)(nil), "house.InputRequest")
	proto.RegisterType((*OutputResponse)(nil), "house.OutputResponse")
	proto.RegisterType((*Err)(nil), "house.Err")
	proto.RegisterType((*Empty)(nil), "house.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HouseService service

type HouseServiceClient interface {
	Input(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*OutputResponse, error)
	Error(ctx context.Context, in *Err, opts ...grpc.CallOption) (*Empty, error)
}

type houseServiceClient struct {
	cc *grpc.ClientConn
}

func NewHouseServiceClient(cc *grpc.ClientConn) HouseServiceClient {
	return &houseServiceClient{cc}
}

func (c *houseServiceClient) Input(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*OutputResponse, error) {
	out := new(OutputResponse)
	err := grpc.Invoke(ctx, "/house.HouseService/Input", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *houseServiceClient) Error(ctx context.Context, in *Err, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/house.HouseService/Error", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HouseService service

type HouseServiceServer interface {
	Input(context.Context, *InputRequest) (*OutputResponse, error)
	Error(context.Context, *Err) (*Empty, error)
}

func RegisterHouseServiceServer(s *grpc.Server, srv HouseServiceServer) {
	s.RegisterService(&_HouseService_serviceDesc, srv)
}

func _HouseService_Input_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseServiceServer).Input(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/house.HouseService/Input",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseServiceServer).Input(ctx, req.(*InputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseService_Error_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Err)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseServiceServer).Error(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/house.HouseService/Error",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseServiceServer).Error(ctx, req.(*Err))
	}
	return interceptor(ctx, in, info, handler)
}

var _HouseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "house.HouseService",
	HandlerType: (*HouseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Input",
			Handler:    _HouseService_Input_Handler,
		},
		{
			MethodName: "Error",
			Handler:    _HouseService_Error_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/house.proto",
}

func init() { proto.RegisterFile("api/house.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcd, 0x4a, 0x3b, 0x31,
	0x14, 0xc5, 0xfb, 0x95, 0x7f, 0xff, 0x5e, 0x86, 0x0a, 0xb1, 0xc2, 0xd0, 0x95, 0x44, 0x44, 0xdd,
	0x74, 0x40, 0xd1, 0x07, 0x10, 0x06, 0x74, 0x25, 0xd4, 0x9d, 0xbb, 0xc9, 0x07, 0x4d, 0xec, 0xc7,
	0x8d, 0x37, 0x89, 0xa0, 0x0f, 0xe1, 0x33, 0x4b, 0x33, 0xad, 0x58, 0xba, 0xbb, 0xbf, 0x73, 0x0e,
	0xe4, 0x70, 0x02, 0xc7, 0x8d, 0x77, 0x95, 0xc5, 0x14, 0xcc, 0xd4, 0x13, 0x46, 0xe4, 0x2c, 0x83,
	0xf8, 0xee, 0x42, 0xf1, 0xb4, 0xf6, 0x29, 0xce, 0xcc, 0x7b, 0x32, 0x21, 0xf2, 0x11, 0xf4, 0x9c,
	0x2e, 0xbb, 0x67, 0xdd, 0xab, 0xa3, 0x59, 0xcf, 0x69, 0x5e, 0xc2, 0xf0, 0xcb, 0x79, 0x85, 0xda,
	0x94, 0xbd, 0x2c, 0xee, 0x90, 0x4f, 0xe0, 0xbf, 0x34, 0x9a, 0x10, 0x57, 0xa1, 0xec, 0x67, 0xeb,
	0x97, 0xf9, 0x18, 0x98, 0x6c, 0xa2, 0x0d, 0xe5, 0x20, 0x1b, 0x2d, 0x70, 0x01, 0xc5, 0xda, 0xb8,
	0xb9, 0x95, 0x48, 0x16, 0x51, 0x97, 0x2c, 0x9b, 0x7b, 0x9a, 0xb8, 0x87, 0xd1, 0x73, 0x8a, 0xb9,
	0x50, 0xf0, 0xb8, 0x0e, 0xe6, 0xa0, 0xd1, 0x18, 0x98, 0x27, 0xa7, 0xda, 0x3e, 0xfd, 0x59, 0x0b,
	0xe2, 0x1a, 0xfa, 0x35, 0xd1, 0x41, 0x98, 0xc3, 0x60, 0x89, 0x21, 0x6c, 0xb3, 0xf9, 0x16, 0x43,
	0x60, 0xf5, 0xca, 0xc7, 0xcf, 0x9b, 0x37, 0x28, 0x1e, 0x37, 0x2b, 0xbc, 0x18, 0xfa, 0x70, 0xca,
	0xf0, 0x3b, 0x60, 0x79, 0x0b, 0x7e, 0x32, 0x6d, 0xa7, 0xfa, 0xbb, 0xcc, 0xe4, 0x74, 0x2b, 0xee,
	0xd7, 0x13, 0x1d, 0x7e, 0x0e, 0xac, 0x26, 0x42, 0xe2, 0xb0, 0x4d, 0xd4, 0x44, 0x93, 0x62, 0x77,
	0x6f, 0x5e, 0x12, 0x9d, 0x87, 0xcb, 0xd7, 0x8b, 0xb9, 0x8b, 0x36, 0xc9, 0xa9, 0xc2, 0x55, 0xb5,
	0x48, 0xd2, 0x28, 0x24, 0x5f, 0x29, 0xa4, 0x66, 0x59, 0x05, 0xbd, 0xa8, 0xe6, 0x58, 0x35, 0x29,
	0x5a, 0xf9, 0x2f, 0xff, 0xcf, 0xed, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x83, 0x38, 0xcc, 0xae,
	0xb2, 0x01, 0x00, 0x00,
}
